version: '3'

services:

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    env_file:
      - ./configs/environment.env
    volumes:
      - ./api/src:/code/src
      - ./api/api.js:/code/api.js
    tty: true
