version: '3'

services:

  api:
    restart: always
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
      - 3002:3002
    env_file:
      - ./config/environment.env
    volumes:
      - ./api/src:/code/src
      - ./api/app.js:/code/app.js
      - ./config:/code/config
      - /mnt/npmap/projects/places-mobile:/places-mobile
    tty: true
    command: ['sh', '-c', 'crond -l 2 -f & node /code/app.js']
